### ISSUE TITLE
Custom logon UI sample

### ISSUE THREAD

**Issue by davidterins** [microsoft/Windows-IoT-Samples#97]
Hi, I am not sure if I have interpreted "custom logon UI" correct in the [documentation](https://learn.microsoft.com/sv-se/windows/iot/iot-enterprise/branding-features/custom-logon). Does a custom UI mean that (1) you can write and provide your own logon UI application/experience and use it as the the logon screen, or (2) is a custom logon UI just the regular windows logon without certain windows specific elements?

<img width="711" alt="2022-10-09_21-51-55" src="https://user-images.githubusercontent.com/25159662/194776740-d208d16f-e3b2-4aa8-b509-f2a91bf573ea.png">

 If (1) is possible, it would be great with a sample in this repo showing how that could be implemented. 👍

**Comment by TerryWarwick** [comment]
@davidterins, it is possible to create a custom experience using a custom credential provider.  For more information about creating a custom logon experience, see [Winlogon and Credential Providers](https://learn.microsoft.com/windows/win32/secauthn/winlogon-and-credential-providers).  We have cross-linked this topic from [Windows IoT Custom Logon](https://learn.microsoft.com/windows/iot/iot-enterprise/branding-features/custom-logon) to make it easier to discover.

**Comment by TerryWarwick** [comment]
Closing thread as answered
